# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHu2-JDe4pMkCX17DIfBKOB5vYyHTDbX
"""

nota = float(input("digite uma nota entre zero e dez:"))
while nota > 10 or nota < 0:
  nota = float(input("digite um valor valido:"))
print("sucesso")

numero = int(input("por favor,digite um numero:"))
contador = 1
while contador <= 10:
 resultado = numero * contador
 print(f"{numero} x {contador} = {resultado}")
 contador +=1

nome = (input("digite o nome do usuario "))
senha=int(input("digite sua senha "))
 while nome == senha:
 print("invalida")
 nome = (input("digite o nome de usuario"))
senha = int(input("digite sua senha"))
print ("valido")

numero = 0
while numero >= 0 and numero <= 9:
  numero += 1
  print(numero)

numero = 0
while numero >= 1 and numero <=21:
  numero +=2
  print(numero)

numero = int(input("digite um numero"))
contador = 1
while contador <= numero:
  print(contador)
  contador += 1

numero = 2
while numero >=0 and numero <=19:
 if numero % 2 == 0:
  numero += 2
  print(numero)

senha = input("Digite sua senha: ")

sen = 134

while sen == 134:
  print("senha invalida")
  senha = input("Digite sua senha valida: ")
print("sucesso")

soma = 0
contador = 0
final = "fim"
print("Digite os números (digite 'fim' para encerrar):")
entrada = int(input("Número "))
while entrada != final:
  entrada = input("Número ")
  soma += num
  contador += 1

if contador > 0:
  media = soma / contador
  print("A media dos numeros é:", media)
else:
  print("nenhum número fornecido")

soma = 0

print("Insira números. Digite 0 para finalizar.")

while:
    numero = int(input("Insira um número: "))

    if numero == 0:
        break

    soma += numero

print("A soma dos números inseridos é:", soma)

print("Digite os números (digite um número negativo para encerrar):")

maior_numero = -9999999999

numero = float(input("Número: "))

while numero >= 0:
    if numero > maior_numero:
        maior_numero = numero
    numero = float(input("Número: "))

if maior_numero != -9999999999:
    print("O maior número inserido foi:", maior_numero)
else:
    print("Nenhum número foi inserido.")