# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CfR4TWZGZ0bW1VwwHz0-bn7nKxVnxS5W
"""

nota =  float (input("Digite uma nota entre zero e dez"))
while nota > 10 or nota < 0:
  nota = float (input ("Digite um valor valido"))
  print ("Sucesso")

n = int(input("Quantas notas deseja inserir? "))
soma = 0
for i in range(n):
  nota = float(input(f"Digite a {i+1}ª nota: "))
  soma += nota
media = soma / n
print(f"A média das notas é {media}")

nome = input("Digite o nome do usuario")
senha = (input(" Digite uma senha "))
while nome == senha:
 print("senha incorreta")
 nome = input(("Digite o nome do usuario"))
 senha = (input(" Digite uma senha "))
print("Sucesso")

ano_contratacao = 1995
salario_inicial = 1000.00
percentual_aumento = 0.015

ano_atual = 1996
while ano_atual <= 2024:
    salario_inicial += salario_inicial * percentual_aumento
    percentual_aumento *= 2
    print("O salário atual do funcionário em", ano_atual, "é: R$", salario_inicial)
    ano_atual += 1



geovanna = input("Digite o nome: ")
while len(geovanna) <= 3:
  geovanna = input("Nome invalido. Digite o nome novamente: ")

idade = int(input("Digite a idade: "))
while idade < 0 or idade > 150:
  idade = int(input("Idade invalida. Digite a idade novamente: "))

salario = float(input("Digite o salário: "))
while salario <= 0:
  salario = float(input("Salário invalido. Digite o salário novamente: "))

sexo = input("Digite o sexo (f/m): ")
while sexo != 'f' and sexo != 'm':
  sexo = input("Sexo invalido. Digite o sexo novamente (f/m): ")

estado_civil = input("Digite o estado civil (s/c/v/d): ")
while estado_civil != 's' and estado_civil != 'c' and estado_civil != 'v' and estado_civil != 'd':
  estado_civil = input("Estado civil invalido. Digite o estado civil novamente (s/c/v/d): ")

print("Dados validados com sucesso!")

